### ISSUE TITLE
What is the exact Beta distribution used here?

### ISSUE THREAD

**Issue by khchul** [kiarashza/GenStat#1]
Thank you for the great work!
I've read your paper and got stuck at
"**where the conditional distribution of the underlying probabilistic adjacency matrix can be modeled as a Beta distribution**" in 3.2.
I've read your supplementary appendix but couldn't find any specifics, i.e, hyper-parameters alpha/beta.
Also the paper you had cited after the quote, '**The continuous bernoulli: fixing a pervasive error in variational autoencoders**', seems to use different distribution.
Could you make some clarification?
Thanks.

**Comment by oschulte** [comment]
Thank you for the nice comment. Yes, this is a bit complex. In Equation 5, we refer to p(\tilde{A}|Z), which is a distribution over soft adjacency matrix with entries in [0,1]. For concreteness, let us focus on \tilde{A}_{ij}, the ij entry. In our most general formulation, \tilde{A}_{ij} is a distribution over [0,1] numbers (link probabilities), so we could have  p(\tilde{A}_{ij}|Z) = Beta(alpha_{ij},beta_{ij}), where the parameters alpha_{ij},beta_{ij} are output by the decoder. We can then sample from the Beta distributions to produce different soft adjacency matrices \tilde{A}. From a soft matrix, we can then sample a hard one A with entries 0 or 1 if we wish. 

As we note in the appendix (Section 7.2), for efficiency in our implementation, we actually don't sample from the Beta distribution and just use the mean E[\tilde{A}_{ij}|Z], which is a Bernoulli parameter, to compute deterministically a soft adjacency matrix from the decoder. This is equivalent to the simpler formulation in our  [Micro-Macro model paper](http://papers.nips.cc/paper/2022/hash/c400474e8a36d0812fdee52739288b12-Abstract-Conference.html). We hope this helps.

**Comment by khchul** [comment]
Thank you!
